title: ابوالفضل تنها
email: abwalfdltnha178@gmail.com
description: >
  یک وبلاگ درباره چیزهای فوق‌العاده.
baseurl: ""  # مسیر پایه است اگر در ریشه است خالی بماند.
url: "https://abwalfdltnha178.github.io"

# تنظیمات چند زبانه
languages:
  - en
  - fa
default_lang: fa

# فارسی سازی
lang: "fa-IR"
dir: "rtl"



# تنظیمات Markdown
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# مشخص کردن برجسته‌ساز
highlighter: rouge

# تنظیمات قالب
theme: minima

# افزونه‌ها
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-multiple-languages-plugin # افزونه چند زبانه

# تنظیمات پیوند دائمی
permalink: /:lang/:categories/:title/

# تنظیمات نویسنده
author:
  name: ابوالفضل تنها
  email: abwalfdltnha178@gmail.com

# تنظیمات اجتماعی
social:
  twitter: abwalfdltnha178
  github: abwalfdltnha178
  linkedin: abwalfdltnha178

# تنظیمات Twitter Card
twitter:
  username: "abwalfdltnha178"

# فعال کردن build افزایشی
incremental: true

# تنظیمات پیش‌فرض بر اساس زبان
defaults:
  - scope:
      path: "_posts/en"
    values:
      lang: "en"
      permalink: "/en/:categories/:title/"
  - scope:
      path: "_posts/fa"
    values:
      lang: "fa"
      permalink: "/fa/:categories/:title/"

# استثناها از ترجمه
exclude_from_localizations:
  - assets
  - images
  - js
  - css
