title: ابوالفضل تنها
email: abwalfdltnha178@gmail.com
description: > 
  یک وبلاگ درباره چیزهای فوق‌العاده.
baseurl: ""  # مسیر پایه است اگر در ریشه است خالی بماند.
url: "https://abwalfdltnha178.github.io"

# فارسی سازی
lang: "fa-IR"
dir: "rtl"

# مشخص کردن برجسته‌ساز
highlighter: rouge

# تنظیمات Markdown
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-syntax # برای استفاده از هایلایت کردن کدها

# تنظیمات پیوند دائمی
permalink: /:categories/:title/

# تنظیمات نویسنده
author:
  name: ابوالفضل تنها
  email: abwalfdltnha178@gmail.com

# تنظیمات اجتماعی
social:
  twitter: abwalfdltnha178
  github: abwalfdltnha178
  linkedin: abwalfdltnha178

# تنظیمات Twitter Card
twitter:
  username: "abwalfdltnha178"

# فعال کردن build افزایشی
incremental: true
