name: ساخت و استقرار AMP با Jekyll

on:
  push:
    branches: [main]  # یا master

permissions:
  contents: write  # اجازه انتشار در gh-pages

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد از مخزن
        uses: actions/checkout@v4

      - name: آماده‌سازی روبی
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: نصب وابستگی‌ها
        run: |
          gem install bundler
          bundle install

      - name: ساخت سایت اصلی با Jekyll
        run: bundle exec jekyll build

      - name: ساخت نسخه AMP سایت
        run: bundle exec jekyll build --destination _site/amp --config _config.yml,_config_amp.yml

      - name: استقرار سایت در GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
