name: ساخت Jekyll با npm

on:
  push:
    branches:
      - main  # یا هر شاخه‌ای که برای GitHub Pages استفاده می‌کنید

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت سورس کد
        uses: actions/checkout@v4

      - name: نصب Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'

      - name: نصب Bundler
        run: gem install bundler

      - name: نصب پکیج‌های پروژه
        run: bundle install

      - name: نصب پکیج‌های npm
        run: npm install

      - name: اجرای Jekyll
        run: bundle exec jekyll build

      - name: انتشار روی GitHub Pages
        uses: actions/upload-pages-artifact@v3