name: Update Algolia Index

on:
  # این Action هنگام push به شاخه main اجرا می‌شود.
  push:
    branches:
      - main

  # این Action به صورت زمان‌بندی‌شده روزانه اجرا می‌شود.
  schedule:
    - cron: '0 0 * * *' # هر روز ساعت 00:00 UTC

  # این Action به صورت دستی نیز می‌تواند اجرا شود.
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build Jekyll site and update Algolia
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        run: bundle exec jekyll algolia
        
