name: Update Algolia Index

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-algolia:
    runs-on: ubuntu-latest

    steps:
      # گام 1: کلون کردن مخزن
      - name: Checkout repository
        uses: actions/checkout@v3

      # گام 2: نصب Ruby و وابستگی‌ها
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true

      # گام 3: نصب وابستگی‌ها
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      # گام 4: تبدیل Markdown به JSON و ارسال به Algolia
      - name: Convert Markdown to JSON and Update Algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        run: |
          mkdir -p data
          bundle exec ruby -e "
            require 'json'
            require 'kramdown'
            require 'algoliasearch'

            # تنظیمات اتصال به Algolia
            client = Algolia::Search::Client.create(ENV['ALGOLIA_APP_ID'], ENV['ALGOLIA_ADMIN_API_KEY'])
            index = client.init_index(ENV['ALGOLIA_INDEX_NAME'])

            # خواندن فایل‌های Markdown
            markdown_files = Dir.glob('_posts/{fa,en}/*.md')
            data = markdown_files.map do |file|
              content = File.read(file)
              parsed_content = Kramdown::Document.new(content, input: 'GFM').to_html
              {
                objectID: File.basename(file, '.md'),
                title: content[/title:\s*(.+)/i, 1],
                lang: file.include?('/fa/') ? 'fa' : 'en',
                date: content[/date:\s*(.+)/i, 1],
                categories: content[/categories:\s*(.+)/i, 1]&.split,
                content: parsed_content
              }
            end

            # ارسال داده‌ها به Algolia
            index.save_objects(data, { autoGenerateObjectIDIfNotExist: true })
            puts '✅ Data successfully updated in Algolia index!'
          "
