name: Update Algolia Index

on:
  push:
    branches:
      - main  # اجرا هنگام هر بار پوش به شاخه main
  workflow_dispatch:  # قابلیت اجرای دستی اکشن

jobs:
  update-algolia:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'  # نسخه Ruby

      - name: Install dependencies
        run: |
          gem install algolia -v '3.7.1'
          gem install json
          gem install kramdown

      - name: Convert Markdown to JSON and Update Algolia
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_ADMIN_API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
        run: |
          ruby -e "
          require 'json'
          require 'algolia'
          require 'kramdown'

          # تابع برای تبدیل فایل‌های مارک‌داون به JSON
          def markdown_to_json(file_path)
            content = File.read(file_path)
            html = Kramdown::Document.new(content).to_html
            {
              title: content[/^# (.+)$/, 1],
              content: html,
              path: file_path
            }
          end

          # جستجوی فایل‌های مارک‌داون
          markdown_files = Dir.glob('_posts/fa/*.md') + Dir.glob('_posts/en/*.md')
          data = markdown_files.map { |file| markdown_to_json(file) }

          # اتصال به Algolia
          client = Algolia::Client.new(application_id: ENV['ALGOLIA_APP_ID'], api_key: ENV['ALGOLIA_ADMIN_API_KEY'])
          index = client.init_index(ENV['ALGOLIA_INDEX_NAME'])

          # ارسال داده‌ها به Algolia
          index.save_objects(data, { autoGenerateObjectIDIfNotExist: true })

          puts 'Data successfully updated in Algolia index!'
          "
